name: Publish

on: 
  workflow_dispatch:
  push:
    branches:
      - Prod

env:
  AZURE_WEBAPP_NAME: Coffee-Machine-Service
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: 8.0.x
            
      - name: Restore
        run: dotnet restore ./CoffeeMachine/CoffeeMachine.csproj

      - name: Build
        run: dotnet build ./CoffeeMachine/CoffeeMachine.csproj --configuration Release --no-restore

      - name: Test
        run: |
          dotnet test \
          --configre Release \ 
          --no build \
          --collect: "XPlat Code Coverage"

      - name: Publish test results
        uses: action/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: '**/TestResults'
      
    
